<?xml version="1.0" encoding="utf-8"?><Database Name="Temiskaming" Class="databaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=WOAD.arvixe.com;Initial Catalog=Temiskaming;Persist Security Info=True;User ID=temismain" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TemiskamingConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.navigation" Member="navigations">
    <Type Name="navigation">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="viewpath" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="controller" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[group]" Member="group" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.jobapplications" Member="jobapplications">
    <Type Name="jobapplication">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="jobtitle" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="aname" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="aphone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="aemail" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="aresume" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="acoverletter" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="anotes" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.jobs" Member="jobs">
    <Type Name="job">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="jobtitle" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="jobdescr" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="posteddate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="qualifications" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="duration" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.admin" Member="admins">
    <Type Name="admin">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="pass" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.doctors" Member="doctors">
    <Type Name="doctor">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="department" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="role" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="program" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="extension" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="office" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="office_hr" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="bio" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="doctor_doctor_schedule" Member="doctor_schedules" ThisKey="Id" OtherKey="doctor_id" Type="doctor_schedule" />
      <Association Name="doctor_appointment" Member="appointments" ThisKey="Id" OtherKey="doctor_id" Type="appointment" />
    </Type>
  </Table>
  <Table Name="dbo.FAQ" Member="FAQs">
    <Type Name="FAQ">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Question" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Answer" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="temismain.news" Member="news">
    <Type Name="news">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.ContactForm" Member="ContactForms">
    <Type Name="ContactForm">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="temismain.doctor_schedules" Member="doctor_schedules">
    <Type Name="doctor_schedule">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="doctor_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="day" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="start_time" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="end_time" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="patient_limit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="doctor_doctor_schedule" Member="doctor" ThisKey="doctor_id" OtherKey="Id" Type="doctor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="temismain.appointments" Member="appointments">
    <Type Name="appointment">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="doctor_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="booking_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="doctor_appointment" Member="doctor" ThisKey="doctor_id" OtherKey="Id" Type="doctor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.waittime" Member="waittimes">
    <Type Name="waittime">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="time_admit" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="time_doctor" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="temismain.chat" Member="chats">
    <Type Name="chat">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="log_file" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="nurse" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="log_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="temismain.email_signups" Member="email_signups">
    <Type Name="email_signup">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ename" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="elname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="eemail" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="temismain.ecards" Member="ecards">
    <Type Name="ecard">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sname" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="rname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="mdate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="urlpath" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="emessage" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="temismain.ecardimages" Member="ecardimages">
    <Type Name="ecardimage">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="urlpath" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="temismain.alerts" Member="alerts">
    <Type Name="alert">
      <Column Name="alertId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="alertTitle" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="alertDescription" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="alertLevel" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="alertTimeline" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="alertStatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.departments" Member="departments">
    <Type Name="department">
      <Column Name="d_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="d_name" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="d_phone" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="d_ext" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="d_fax" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="department_staff" Member="staffs" ThisKey="d_id" OtherKey="staff_departmentId" Type="staff" />
    </Type>
  </Table>
  <Table Name="dbo.staffs" Member="staffs">
    <Type Name="staff">
      <Column Name="staff_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="staff_fname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="staff_lname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="staff_position" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="staff_phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="staff_ext" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="staff_email" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="staff_departmentName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="staff_departmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="department_staff" Member="department" ThisKey="staff_departmentId" OtherKey="d_id" Type="department" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="temismain.donation" Member="donations">
    <Type Name="donation">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="first_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="last_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="message" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="donation_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="verify" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.story" Member="stories">
    <Type Name="story">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="author" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="story" Member="story1" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="published" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.volunteer_opportunities" Member="volunteer_opportunities">
    <Type Name="volunteer_opportunity">
      <Column Name="o_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="o_name" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="o_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="o_start" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="o_end" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="o_day" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="o_location" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="o_description" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Association Name="volunteer_opportunity_volunteer" Member="volunteers" ThisKey="o_id" OtherKey="v_opportunityId" Type="volunteer" />
      <Association Name="volunteer_opportunity_volunteer_schedule" Member="volunteer_schedules" ThisKey="o_id" OtherKey="o_id" Type="volunteer_schedule" />
    </Type>
  </Table>
  <Table Name="dbo.volunteers" Member="volunteers">
    <Type Name="volunteer">
      <Column Name="v_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="v_fname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="v_lname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="v_address" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="v_city" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="v_province" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="v_postalCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="v_phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="v_email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="v_opportunityId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="volunteer_volunteer_schedule" Member="volunteer_schedules" ThisKey="v_id" OtherKey="v_id" Type="volunteer_schedule" />
      <Association Name="volunteer_opportunity_volunteer" Member="volunteer_opportunity" ThisKey="v_opportunityId" OtherKey="o_id" Type="volunteer_opportunity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.volunteer_schedules" Member="volunteer_schedules">
    <Type Name="volunteer_schedule">
      <Column Name="s_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="o_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="v_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="s_status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="s_detail" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="s_day" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="volunteer_opportunity_volunteer_schedule" Member="volunteer_opportunity" ThisKey="o_id" OtherKey="o_id" Type="volunteer_opportunity" IsForeignKey="true" />
      <Association Name="volunteer_volunteer_schedule" Member="volunteer" ThisKey="v_id" OtherKey="v_id" Type="volunteer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Gifts" Member="Gifts">
    <Type Name="Gift">
      <Column Name="ItemId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Item" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Inventory" Type="System.Decimal" DbType="Decimal(4,0) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="temismain.polls" Member="polls">
    <Type Name="poll">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="question" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="option1" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="option2" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="choice1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="choice2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="published" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="OrderId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderDate" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="ToPatient" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="[From]" Member="From" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="itemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>