#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temiskaming.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Temiskaming")]
	public partial class databaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertnavigation(navigation instance);
    partial void Updatenavigation(navigation instance);
    partial void Deletenavigation(navigation instance);
    partial void Insertjobapplication(jobapplication instance);
    partial void Updatejobapplication(jobapplication instance);
    partial void Deletejobapplication(jobapplication instance);
    partial void Insertjob(job instance);
    partial void Updatejob(job instance);
    partial void Deletejob(job instance);
    partial void Insertadmin(admin instance);
    partial void Updateadmin(admin instance);
    partial void Deleteadmin(admin instance);
    partial void Insertdoctor(doctor instance);
    partial void Updatedoctor(doctor instance);
    partial void Deletedoctor(doctor instance);
    partial void InsertFAQ(FAQ instance);
    partial void UpdateFAQ(FAQ instance);
    partial void DeleteFAQ(FAQ instance);
    partial void Insertnews(news instance);
    partial void Updatenews(news instance);
    partial void Deletenews(news instance);
    partial void InsertContactForm(ContactForm instance);
    partial void UpdateContactForm(ContactForm instance);
    partial void DeleteContactForm(ContactForm instance);
    partial void Insertdoctor_schedule(doctor_schedule instance);
    partial void Updatedoctor_schedule(doctor_schedule instance);
    partial void Deletedoctor_schedule(doctor_schedule instance);
    partial void Insertappointment(appointment instance);
    partial void Updateappointment(appointment instance);
    partial void Deleteappointment(appointment instance);
    partial void Insertwaittime(waittime instance);
    partial void Updatewaittime(waittime instance);
    partial void Deletewaittime(waittime instance);
    partial void Insertchat(chat instance);
    partial void Updatechat(chat instance);
    partial void Deletechat(chat instance);
    partial void Insertemail_signup(email_signup instance);
    partial void Updateemail_signup(email_signup instance);
    partial void Deleteemail_signup(email_signup instance);
    partial void Insertecard(ecard instance);
    partial void Updateecard(ecard instance);
    partial void Deleteecard(ecard instance);
    partial void Insertecardimage(ecardimage instance);
    partial void Updateecardimage(ecardimage instance);
    partial void Deleteecardimage(ecardimage instance);
    partial void Insertalert(alert instance);
    partial void Updatealert(alert instance);
    partial void Deletealert(alert instance);
    partial void Insertdepartment(department instance);
    partial void Updatedepartment(department instance);
    partial void Deletedepartment(department instance);
    partial void Insertstaff(staff instance);
    partial void Updatestaff(staff instance);
    partial void Deletestaff(staff instance);
    partial void Insertdonation(donation instance);
    partial void Updatedonation(donation instance);
    partial void Deletedonation(donation instance);
    #endregion
		
		public databaseDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TemiskamingConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<navigation> navigations
		{
			get
			{
				return this.GetTable<navigation>();
			}
		}
		
		public System.Data.Linq.Table<jobapplication> jobapplications
		{
			get
			{
				return this.GetTable<jobapplication>();
			}
		}
		
		public System.Data.Linq.Table<job> jobs
		{
			get
			{
				return this.GetTable<job>();
			}
		}
		
		public System.Data.Linq.Table<admin> admins
		{
			get
			{
				return this.GetTable<admin>();
			}
		}
		
		public System.Data.Linq.Table<doctor> doctors
		{
			get
			{
				return this.GetTable<doctor>();
			}
		}
		
		public System.Data.Linq.Table<FAQ> FAQs
		{
			get
			{
				return this.GetTable<FAQ>();
			}
		}
		
		public System.Data.Linq.Table<news> news
		{
			get
			{
				return this.GetTable<news>();
			}
		}
		
		public System.Data.Linq.Table<ContactForm> ContactForms
		{
			get
			{
				return this.GetTable<ContactForm>();
			}
		}
		
		public System.Data.Linq.Table<doctor_schedule> doctor_schedules
		{
			get
			{
				return this.GetTable<doctor_schedule>();
			}
		}
		
		public System.Data.Linq.Table<appointment> appointments
		{
			get
			{
				return this.GetTable<appointment>();
			}
		}
		
		public System.Data.Linq.Table<waittime> waittimes
		{
			get
			{
				return this.GetTable<waittime>();
			}
		}
		
		public System.Data.Linq.Table<chat> chats
		{
			get
			{
				return this.GetTable<chat>();
			}
		}
		
		public System.Data.Linq.Table<email_signup> email_signups
		{
			get
			{
				return this.GetTable<email_signup>();
			}
		}
		
		public System.Data.Linq.Table<ecard> ecards
		{
			get
			{
				return this.GetTable<ecard>();
			}
		}
		
		public System.Data.Linq.Table<ecardimage> ecardimages
		{
			get
			{
				return this.GetTable<ecardimage>();
			}
		}
		
		public System.Data.Linq.Table<alert> alerts
		{
			get
			{
				return this.GetTable<alert>();
			}
		}
		
		public System.Data.Linq.Table<department> departments
		{
			get
			{
				return this.GetTable<department>();
			}
		}
		
		public System.Data.Linq.Table<staff> staffs
		{
			get
			{
				return this.GetTable<staff>();
			}
		}
		
		public System.Data.Linq.Table<donation> donations
		{
			get
			{
				return this.GetTable<donation>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.navigation")]
	public partial class navigation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _viewpath;
		
		private string _controller;
		
		private string _group;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnviewpathChanging(string value);
    partial void OnviewpathChanged();
    partial void OncontrollerChanging(string value);
    partial void OncontrollerChanged();
    partial void OngroupChanging(string value);
    partial void OngroupChanged();
    #endregion
		
		public navigation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_viewpath", DbType="VarChar(50)")]
		public string viewpath
		{
			get
			{
				return this._viewpath;
			}
			set
			{
				if ((this._viewpath != value))
				{
					this.OnviewpathChanging(value);
					this.SendPropertyChanging();
					this._viewpath = value;
					this.SendPropertyChanged("viewpath");
					this.OnviewpathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_controller", DbType="VarChar(50)")]
		public string controller
		{
			get
			{
				return this._controller;
			}
			set
			{
				if ((this._controller != value))
				{
					this.OncontrollerChanging(value);
					this.SendPropertyChanging();
					this._controller = value;
					this.SendPropertyChanged("controller");
					this.OncontrollerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[group]", Storage="_group", DbType="VarChar(50)")]
		public string group
		{
			get
			{
				return this._group;
			}
			set
			{
				if ((this._group != value))
				{
					this.OngroupChanging(value);
					this.SendPropertyChanging();
					this._group = value;
					this.SendPropertyChanged("group");
					this.OngroupChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.jobapplications")]
	public partial class jobapplication : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _jobtitle;
		
		private string _aname;
		
		private string _aphone;
		
		private string _aemail;
		
		private string _aresume;
		
		private string _acoverletter;
		
		private string _anotes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnjobtitleChanging(string value);
    partial void OnjobtitleChanged();
    partial void OnanameChanging(string value);
    partial void OnanameChanged();
    partial void OnaphoneChanging(string value);
    partial void OnaphoneChanged();
    partial void OnaemailChanging(string value);
    partial void OnaemailChanged();
    partial void OnaresumeChanging(string value);
    partial void OnaresumeChanged();
    partial void OnacoverletterChanging(string value);
    partial void OnacoverletterChanged();
    partial void OnanotesChanging(string value);
    partial void OnanotesChanged();
    #endregion
		
		public jobapplication()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobtitle", DbType="VarChar(MAX)")]
		public string jobtitle
		{
			get
			{
				return this._jobtitle;
			}
			set
			{
				if ((this._jobtitle != value))
				{
					this.OnjobtitleChanging(value);
					this.SendPropertyChanging();
					this._jobtitle = value;
					this.SendPropertyChanged("jobtitle");
					this.OnjobtitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aname", DbType="VarChar(MAX)")]
		public string aname
		{
			get
			{
				return this._aname;
			}
			set
			{
				if ((this._aname != value))
				{
					this.OnanameChanging(value);
					this.SendPropertyChanging();
					this._aname = value;
					this.SendPropertyChanged("aname");
					this.OnanameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aphone", DbType="VarChar(50)")]
		public string aphone
		{
			get
			{
				return this._aphone;
			}
			set
			{
				if ((this._aphone != value))
				{
					this.OnaphoneChanging(value);
					this.SendPropertyChanging();
					this._aphone = value;
					this.SendPropertyChanged("aphone");
					this.OnaphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aemail", DbType="VarChar(MAX)")]
		public string aemail
		{
			get
			{
				return this._aemail;
			}
			set
			{
				if ((this._aemail != value))
				{
					this.OnaemailChanging(value);
					this.SendPropertyChanging();
					this._aemail = value;
					this.SendPropertyChanged("aemail");
					this.OnaemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aresume", DbType="VarChar(MAX)")]
		public string aresume
		{
			get
			{
				return this._aresume;
			}
			set
			{
				if ((this._aresume != value))
				{
					this.OnaresumeChanging(value);
					this.SendPropertyChanging();
					this._aresume = value;
					this.SendPropertyChanged("aresume");
					this.OnaresumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acoverletter", DbType="VarChar(MAX)")]
		public string acoverletter
		{
			get
			{
				return this._acoverletter;
			}
			set
			{
				if ((this._acoverletter != value))
				{
					this.OnacoverletterChanging(value);
					this.SendPropertyChanging();
					this._acoverletter = value;
					this.SendPropertyChanged("acoverletter");
					this.OnacoverletterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anotes", DbType="VarChar(MAX)")]
		public string anotes
		{
			get
			{
				return this._anotes;
			}
			set
			{
				if ((this._anotes != value))
				{
					this.OnanotesChanging(value);
					this.SendPropertyChanging();
					this._anotes = value;
					this.SendPropertyChanged("anotes");
					this.OnanotesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.jobs")]
	public partial class job : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _jobtitle;
		
		private string _jobdescr;
		
		private System.Nullable<System.DateTime> _posteddate;
		
		private string _qualifications;
		
		private string _duration;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnjobtitleChanging(string value);
    partial void OnjobtitleChanged();
    partial void OnjobdescrChanging(string value);
    partial void OnjobdescrChanged();
    partial void OnposteddateChanging(System.Nullable<System.DateTime> value);
    partial void OnposteddateChanged();
    partial void OnqualificationsChanging(string value);
    partial void OnqualificationsChanged();
    partial void OndurationChanging(string value);
    partial void OndurationChanged();
    #endregion
		
		public job()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobtitle", DbType="VarChar(50)")]
		public string jobtitle
		{
			get
			{
				return this._jobtitle;
			}
			set
			{
				if ((this._jobtitle != value))
				{
					this.OnjobtitleChanging(value);
					this.SendPropertyChanging();
					this._jobtitle = value;
					this.SendPropertyChanged("jobtitle");
					this.OnjobtitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobdescr", DbType="VarChar(MAX)")]
		public string jobdescr
		{
			get
			{
				return this._jobdescr;
			}
			set
			{
				if ((this._jobdescr != value))
				{
					this.OnjobdescrChanging(value);
					this.SendPropertyChanging();
					this._jobdescr = value;
					this.SendPropertyChanged("jobdescr");
					this.OnjobdescrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_posteddate", DbType="Date")]
		public System.Nullable<System.DateTime> posteddate
		{
			get
			{
				return this._posteddate;
			}
			set
			{
				if ((this._posteddate != value))
				{
					this.OnposteddateChanging(value);
					this.SendPropertyChanging();
					this._posteddate = value;
					this.SendPropertyChanged("posteddate");
					this.OnposteddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qualifications", DbType="VarChar(MAX)")]
		public string qualifications
		{
			get
			{
				return this._qualifications;
			}
			set
			{
				if ((this._qualifications != value))
				{
					this.OnqualificationsChanging(value);
					this.SendPropertyChanging();
					this._qualifications = value;
					this.SendPropertyChanged("qualifications");
					this.OnqualificationsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duration", DbType="VarChar(MAX)")]
		public string duration
		{
			get
			{
				return this._duration;
			}
			set
			{
				if ((this._duration != value))
				{
					this.OndurationChanging(value);
					this.SendPropertyChanging();
					this._duration = value;
					this.SendPropertyChanged("duration");
					this.OndurationChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin")]
	public partial class admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _login;
		
		private string _pass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnloginChanging(string value);
    partial void OnloginChanged();
    partial void OnpassChanging(string value);
    partial void OnpassChanged();
    #endregion
		
		public admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login", DbType="VarChar(50)")]
		public string login
		{
			get
			{
				return this._login;
			}
			set
			{
				if ((this._login != value))
				{
					this.OnloginChanging(value);
					this.SendPropertyChanging();
					this._login = value;
					this.SendPropertyChanged("login");
					this.OnloginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass", DbType="VarChar(20)")]
		public string pass
		{
			get
			{
				return this._pass;
			}
			set
			{
				if ((this._pass != value))
				{
					this.OnpassChanging(value);
					this.SendPropertyChanging();
					this._pass = value;
					this.SendPropertyChanged("pass");
					this.OnpassChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.doctors")]
	public partial class doctor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _fname;
		
		private string _lname;
		
		private string _title;
		
		private string _department;
		
		private string _role;
		
		private string _program;
		
		private string _status;
		
		private string _email;
		
		private string _extension;
		
		private string _phone;
		
		private string _office;
		
		private string _office_hr;
		
		private string _bio;
		
		private EntitySet<doctor_schedule> _doctor_schedules;
		
		private EntitySet<appointment> _appointments;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnfnameChanging(string value);
    partial void OnfnameChanged();
    partial void OnlnameChanging(string value);
    partial void OnlnameChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OndepartmentChanging(string value);
    partial void OndepartmentChanged();
    partial void OnroleChanging(string value);
    partial void OnroleChanged();
    partial void OnprogramChanging(string value);
    partial void OnprogramChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnextensionChanging(string value);
    partial void OnextensionChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnofficeChanging(string value);
    partial void OnofficeChanged();
    partial void Onoffice_hrChanging(string value);
    partial void Onoffice_hrChanged();
    partial void OnbioChanging(string value);
    partial void OnbioChanged();
    #endregion
		
		public doctor()
		{
			this._doctor_schedules = new EntitySet<doctor_schedule>(new Action<doctor_schedule>(this.attach_doctor_schedules), new Action<doctor_schedule>(this.detach_doctor_schedules));
			this._appointments = new EntitySet<appointment>(new Action<appointment>(this.attach_appointments), new Action<appointment>(this.detach_appointments));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string fname
		{
			get
			{
				return this._fname;
			}
			set
			{
				if ((this._fname != value))
				{
					this.OnfnameChanging(value);
					this.SendPropertyChanging();
					this._fname = value;
					this.SendPropertyChanged("fname");
					this.OnfnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string lname
		{
			get
			{
				return this._lname;
			}
			set
			{
				if ((this._lname != value))
				{
					this.OnlnameChanging(value);
					this.SendPropertyChanging();
					this._lname = value;
					this.SendPropertyChanged("lname");
					this.OnlnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string department
		{
			get
			{
				return this._department;
			}
			set
			{
				if ((this._department != value))
				{
					this.OndepartmentChanging(value);
					this.SendPropertyChanging();
					this._department = value;
					this.SendPropertyChanged("department");
					this.OndepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="VarChar(50)")]
		public string role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_program", DbType="VarChar(50)")]
		public string program
		{
			get
			{
				return this._program;
			}
			set
			{
				if ((this._program != value))
				{
					this.OnprogramChanging(value);
					this.SendPropertyChanging();
					this._program = value;
					this.SendPropertyChanged("program");
					this.OnprogramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(50)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_extension", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string extension
		{
			get
			{
				return this._extension;
			}
			set
			{
				if ((this._extension != value))
				{
					this.OnextensionChanging(value);
					this.SendPropertyChanging();
					this._extension = value;
					this.SendPropertyChanged("extension");
					this.OnextensionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(50)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_office", DbType="VarChar(50)")]
		public string office
		{
			get
			{
				return this._office;
			}
			set
			{
				if ((this._office != value))
				{
					this.OnofficeChanging(value);
					this.SendPropertyChanging();
					this._office = value;
					this.SendPropertyChanged("office");
					this.OnofficeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_office_hr", DbType="VarChar(50)")]
		public string office_hr
		{
			get
			{
				return this._office_hr;
			}
			set
			{
				if ((this._office_hr != value))
				{
					this.Onoffice_hrChanging(value);
					this.SendPropertyChanging();
					this._office_hr = value;
					this.SendPropertyChanged("office_hr");
					this.Onoffice_hrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bio", DbType="VarChar(MAX)")]
		public string bio
		{
			get
			{
				return this._bio;
			}
			set
			{
				if ((this._bio != value))
				{
					this.OnbioChanging(value);
					this.SendPropertyChanging();
					this._bio = value;
					this.SendPropertyChanged("bio");
					this.OnbioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="doctor_doctor_schedule", Storage="_doctor_schedules", ThisKey="Id", OtherKey="doctor_id")]
		public EntitySet<doctor_schedule> doctor_schedules
		{
			get
			{
				return this._doctor_schedules;
			}
			set
			{
				this._doctor_schedules.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="doctor_appointment", Storage="_appointments", ThisKey="Id", OtherKey="doctor_id")]
		public EntitySet<appointment> appointments
		{
			get
			{
				return this._appointments;
			}
			set
			{
				this._appointments.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_doctor_schedules(doctor_schedule entity)
		{
			this.SendPropertyChanging();
			entity.doctor = this;
		}
		
		private void detach_doctor_schedules(doctor_schedule entity)
		{
			this.SendPropertyChanging();
			entity.doctor = null;
		}
		
		private void attach_appointments(appointment entity)
		{
			this.SendPropertyChanging();
			entity.doctor = this;
		}
		
		private void detach_appointments(appointment entity)
		{
			this.SendPropertyChanging();
			entity.doctor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FAQ")]
	public partial class FAQ : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Question;
		
		private string _Answer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnQuestionChanging(string value);
    partial void OnQuestionChanged();
    partial void OnAnswerChanging(string value);
    partial void OnAnswerChanged();
    #endregion
		
		public FAQ()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question", DbType="VarChar(MAX)")]
		public string Question
		{
			get
			{
				return this._Question;
			}
			set
			{
				if ((this._Question != value))
				{
					this.OnQuestionChanging(value);
					this.SendPropertyChanging();
					this._Question = value;
					this.SendPropertyChanged("Question");
					this.OnQuestionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answer", DbType="VarChar(MAX)")]
		public string Answer
		{
			get
			{
				return this._Answer;
			}
			set
			{
				if ((this._Answer != value))
				{
					this.OnAnswerChanging(value);
					this.SendPropertyChanging();
					this._Answer = value;
					this.SendPropertyChanged("Answer");
					this.OnAnswerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="temismain.news")]
	public partial class news : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _title;
		
		private string _content;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OncontentChanging(string value);
    partial void OncontentChanged();
    #endregion
		
		public news()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this.OncontentChanging(value);
					this.SendPropertyChanging();
					this._content = value;
					this.SendPropertyChanged("content");
					this.OncontentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ContactForm")]
	public partial class ContactForm : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Name;
		
		private string _Email;
		
		private string _Comment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    #endregion
		
		public ContactForm()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="temismain.doctor_schedules")]
	public partial class doctor_schedule : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _doctor_id;
		
		private string _day;
		
		private System.TimeSpan _start_time;
		
		private System.TimeSpan _end_time;
		
		private System.Nullable<int> _patient_limit;
		
		private EntityRef<doctor> _doctor;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Ondoctor_idChanging(int value);
    partial void Ondoctor_idChanged();
    partial void OndayChanging(string value);
    partial void OndayChanged();
    partial void Onstart_timeChanging(System.TimeSpan value);
    partial void Onstart_timeChanged();
    partial void Onend_timeChanging(System.TimeSpan value);
    partial void Onend_timeChanged();
    partial void Onpatient_limitChanging(System.Nullable<int> value);
    partial void Onpatient_limitChanged();
    #endregion
		
		public doctor_schedule()
		{
			this._doctor = default(EntityRef<doctor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doctor_id", DbType="Int NOT NULL")]
		public int doctor_id
		{
			get
			{
				return this._doctor_id;
			}
			set
			{
				if ((this._doctor_id != value))
				{
					if (this._doctor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondoctor_idChanging(value);
					this.SendPropertyChanging();
					this._doctor_id = value;
					this.SendPropertyChanged("doctor_id");
					this.Ondoctor_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_day", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string day
		{
			get
			{
				return this._day;
			}
			set
			{
				if ((this._day != value))
				{
					this.OndayChanging(value);
					this.SendPropertyChanging();
					this._day = value;
					this.SendPropertyChanged("day");
					this.OndayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_time", DbType="Time NOT NULL")]
		public System.TimeSpan start_time
		{
			get
			{
				return this._start_time;
			}
			set
			{
				if ((this._start_time != value))
				{
					this.Onstart_timeChanging(value);
					this.SendPropertyChanging();
					this._start_time = value;
					this.SendPropertyChanged("start_time");
					this.Onstart_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_time", DbType="Time NOT NULL")]
		public System.TimeSpan end_time
		{
			get
			{
				return this._end_time;
			}
			set
			{
				if ((this._end_time != value))
				{
					this.Onend_timeChanging(value);
					this.SendPropertyChanging();
					this._end_time = value;
					this.SendPropertyChanged("end_time");
					this.Onend_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_patient_limit", DbType="Int")]
		public System.Nullable<int> patient_limit
		{
			get
			{
				return this._patient_limit;
			}
			set
			{
				if ((this._patient_limit != value))
				{
					this.Onpatient_limitChanging(value);
					this.SendPropertyChanging();
					this._patient_limit = value;
					this.SendPropertyChanged("patient_limit");
					this.Onpatient_limitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="doctor_doctor_schedule", Storage="_doctor", ThisKey="doctor_id", OtherKey="Id", IsForeignKey=true)]
		public doctor doctor
		{
			get
			{
				return this._doctor.Entity;
			}
			set
			{
				doctor previousValue = this._doctor.Entity;
				if (((previousValue != value) 
							|| (this._doctor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._doctor.Entity = null;
						previousValue.doctor_schedules.Remove(this);
					}
					this._doctor.Entity = value;
					if ((value != null))
					{
						value.doctor_schedules.Add(this);
						this._doctor_id = value.Id;
					}
					else
					{
						this._doctor_id = default(int);
					}
					this.SendPropertyChanged("doctor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="temismain.appointments")]
	public partial class appointment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _doctor_id;
		
		private System.DateTime _booking_date;
		
		private string _email;
		
		private string _phone;
		
		private EntityRef<doctor> _doctor;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Ondoctor_idChanging(int value);
    partial void Ondoctor_idChanged();
    partial void Onbooking_dateChanging(System.DateTime value);
    partial void Onbooking_dateChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    #endregion
		
		public appointment()
		{
			this._doctor = default(EntityRef<doctor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doctor_id", DbType="Int NOT NULL")]
		public int doctor_id
		{
			get
			{
				return this._doctor_id;
			}
			set
			{
				if ((this._doctor_id != value))
				{
					if (this._doctor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondoctor_idChanging(value);
					this.SendPropertyChanging();
					this._doctor_id = value;
					this.SendPropertyChanged("doctor_id");
					this.Ondoctor_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_booking_date", DbType="Date NOT NULL")]
		public System.DateTime booking_date
		{
			get
			{
				return this._booking_date;
			}
			set
			{
				if ((this._booking_date != value))
				{
					this.Onbooking_dateChanging(value);
					this.SendPropertyChanging();
					this._booking_date = value;
					this.SendPropertyChanged("booking_date");
					this.Onbooking_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="doctor_appointment", Storage="_doctor", ThisKey="doctor_id", OtherKey="Id", IsForeignKey=true)]
		public doctor doctor
		{
			get
			{
				return this._doctor.Entity;
			}
			set
			{
				doctor previousValue = this._doctor.Entity;
				if (((previousValue != value) 
							|| (this._doctor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._doctor.Entity = null;
						previousValue.appointments.Remove(this);
					}
					this._doctor.Entity = value;
					if ((value != null))
					{
						value.appointments.Add(this);
						this._doctor_id = value.Id;
					}
					else
					{
						this._doctor_id = default(int);
					}
					this.SendPropertyChanged("doctor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.waittime")]
	public partial class waittime : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private System.DateTime _time_admit;
		
		private System.Nullable<System.DateTime> _time_doctor;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Ontime_admitChanging(System.DateTime value);
    partial void Ontime_admitChanged();
    partial void Ontime_doctorChanging(System.Nullable<System.DateTime> value);
    partial void Ontime_doctorChanged();
    #endregion
		
		public waittime()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time_admit", DbType="DateTime2 NOT NULL")]
		public System.DateTime time_admit
		{
			get
			{
				return this._time_admit;
			}
			set
			{
				if ((this._time_admit != value))
				{
					this.Ontime_admitChanging(value);
					this.SendPropertyChanging();
					this._time_admit = value;
					this.SendPropertyChanged("time_admit");
					this.Ontime_admitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time_doctor", DbType="DateTime2")]
		public System.Nullable<System.DateTime> time_doctor
		{
			get
			{
				return this._time_doctor;
			}
			set
			{
				if ((this._time_doctor != value))
				{
					this.Ontime_doctorChanging(value);
					this.SendPropertyChanging();
					this._time_doctor = value;
					this.SendPropertyChanged("time_doctor");
					this.Ontime_doctorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="temismain.chat")]
	public partial class chat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _email;
		
		private string _log_file;
		
		private string _nurse;
		
		private System.Nullable<System.DateTime> _log_date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onlog_fileChanging(string value);
    partial void Onlog_fileChanged();
    partial void OnnurseChanging(string value);
    partial void OnnurseChanged();
    partial void Onlog_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onlog_dateChanged();
    #endregion
		
		public chat()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_file", DbType="VarChar(100)")]
		public string log_file
		{
			get
			{
				return this._log_file;
			}
			set
			{
				if ((this._log_file != value))
				{
					this.Onlog_fileChanging(value);
					this.SendPropertyChanging();
					this._log_file = value;
					this.SendPropertyChanged("log_file");
					this.Onlog_fileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nurse", DbType="VarChar(50)")]
		public string nurse
		{
			get
			{
				return this._nurse;
			}
			set
			{
				if ((this._nurse != value))
				{
					this.OnnurseChanging(value);
					this.SendPropertyChanging();
					this._nurse = value;
					this.SendPropertyChanged("nurse");
					this.OnnurseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> log_date
		{
			get
			{
				return this._log_date;
			}
			set
			{
				if ((this._log_date != value))
				{
					this.Onlog_dateChanging(value);
					this.SendPropertyChanging();
					this._log_date = value;
					this.SendPropertyChanged("log_date");
					this.Onlog_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="temismain.email_signups")]
	public partial class email_signup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _ename;
		
		private string _elname;
		
		private string _eemail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnenameChanging(string value);
    partial void OnenameChanged();
    partial void OnelnameChanging(string value);
    partial void OnelnameChanged();
    partial void OneemailChanging(string value);
    partial void OneemailChanged();
    #endregion
		
		public email_signup()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ename", DbType="NVarChar(MAX)")]
		public string ename
		{
			get
			{
				return this._ename;
			}
			set
			{
				if ((this._ename != value))
				{
					this.OnenameChanging(value);
					this.SendPropertyChanging();
					this._ename = value;
					this.SendPropertyChanged("ename");
					this.OnenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_elname", DbType="NVarChar(50)")]
		public string elname
		{
			get
			{
				return this._elname;
			}
			set
			{
				if ((this._elname != value))
				{
					this.OnelnameChanging(value);
					this.SendPropertyChanging();
					this._elname = value;
					this.SendPropertyChanged("elname");
					this.OnelnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eemail", DbType="NVarChar(MAX)")]
		public string eemail
		{
			get
			{
				return this._eemail;
			}
			set
			{
				if ((this._eemail != value))
				{
					this.OneemailChanging(value);
					this.SendPropertyChanging();
					this._eemail = value;
					this.SendPropertyChanged("eemail");
					this.OneemailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="temismain.ecards")]
	public partial class ecard : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _sname;
		
		private string _rname;
		
		private System.DateTime _mdate;
		
		private string _urlpath;
		
		private string _emessage;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnsnameChanging(string value);
    partial void OnsnameChanged();
    partial void OnrnameChanging(string value);
    partial void OnrnameChanged();
    partial void OnmdateChanging(System.DateTime value);
    partial void OnmdateChanged();
    partial void OnurlpathChanging(string value);
    partial void OnurlpathChanged();
    partial void OnemessageChanging(string value);
    partial void OnemessageChanged();
    #endregion
		
		public ecard()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sname", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string sname
		{
			get
			{
				return this._sname;
			}
			set
			{
				if ((this._sname != value))
				{
					this.OnsnameChanging(value);
					this.SendPropertyChanging();
					this._sname = value;
					this.SendPropertyChanged("sname");
					this.OnsnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string rname
		{
			get
			{
				return this._rname;
			}
			set
			{
				if ((this._rname != value))
				{
					this.OnrnameChanging(value);
					this.SendPropertyChanging();
					this._rname = value;
					this.SendPropertyChanged("rname");
					this.OnrnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mdate", DbType="Date NOT NULL")]
		public System.DateTime mdate
		{
			get
			{
				return this._mdate;
			}
			set
			{
				if ((this._mdate != value))
				{
					this.OnmdateChanging(value);
					this.SendPropertyChanging();
					this._mdate = value;
					this.SendPropertyChanged("mdate");
					this.OnmdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlpath", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string urlpath
		{
			get
			{
				return this._urlpath;
			}
			set
			{
				if ((this._urlpath != value))
				{
					this.OnurlpathChanging(value);
					this.SendPropertyChanging();
					this._urlpath = value;
					this.SendPropertyChanged("urlpath");
					this.OnurlpathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emessage", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string emessage
		{
			get
			{
				return this._emessage;
			}
			set
			{
				if ((this._emessage != value))
				{
					this.OnemessageChanging(value);
					this.SendPropertyChanging();
					this._emessage = value;
					this.SendPropertyChanged("emessage");
					this.OnemessageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="temismain.ecardimages")]
	public partial class ecardimage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _urlpath;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnurlpathChanging(string value);
    partial void OnurlpathChanged();
    #endregion
		
		public ecardimage()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlpath", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string urlpath
		{
			get
			{
				return this._urlpath;
			}
			set
			{
				if ((this._urlpath != value))
				{
					this.OnurlpathChanging(value);
					this.SendPropertyChanging();
					this._urlpath = value;
					this.SendPropertyChanged("urlpath");
					this.OnurlpathChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="temismain.alerts")]
	public partial class alert : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _alertId;
		
		private string _alertTitle;
		
		private string _alertDescription;
		
		private string _alertLevel;
		
		private System.Nullable<System.DateTime> _alertTimeline;
		
		private System.Nullable<bool> _alertStatus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnalertIdChanging(int value);
    partial void OnalertIdChanged();
    partial void OnalertTitleChanging(string value);
    partial void OnalertTitleChanged();
    partial void OnalertDescriptionChanging(string value);
    partial void OnalertDescriptionChanged();
    partial void OnalertLevelChanging(string value);
    partial void OnalertLevelChanged();
    partial void OnalertTimelineChanging(System.Nullable<System.DateTime> value);
    partial void OnalertTimelineChanged();
    partial void OnalertStatusChanging(System.Nullable<bool> value);
    partial void OnalertStatusChanged();
    #endregion
		
		public alert()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alertId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int alertId
		{
			get
			{
				return this._alertId;
			}
			set
			{
				if ((this._alertId != value))
				{
					this.OnalertIdChanging(value);
					this.SendPropertyChanging();
					this._alertId = value;
					this.SendPropertyChanged("alertId");
					this.OnalertIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alertTitle", DbType="VarChar(100)")]
		public string alertTitle
		{
			get
			{
				return this._alertTitle;
			}
			set
			{
				if ((this._alertTitle != value))
				{
					this.OnalertTitleChanging(value);
					this.SendPropertyChanging();
					this._alertTitle = value;
					this.SendPropertyChanged("alertTitle");
					this.OnalertTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alertDescription", DbType="VarChar(MAX)")]
		public string alertDescription
		{
			get
			{
				return this._alertDescription;
			}
			set
			{
				if ((this._alertDescription != value))
				{
					this.OnalertDescriptionChanging(value);
					this.SendPropertyChanging();
					this._alertDescription = value;
					this.SendPropertyChanged("alertDescription");
					this.OnalertDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alertLevel", DbType="VarChar(10)")]
		public string alertLevel
		{
			get
			{
				return this._alertLevel;
			}
			set
			{
				if ((this._alertLevel != value))
				{
					this.OnalertLevelChanging(value);
					this.SendPropertyChanging();
					this._alertLevel = value;
					this.SendPropertyChanged("alertLevel");
					this.OnalertLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alertTimeline", DbType="DateTime")]
		public System.Nullable<System.DateTime> alertTimeline
		{
			get
			{
				return this._alertTimeline;
			}
			set
			{
				if ((this._alertTimeline != value))
				{
					this.OnalertTimelineChanging(value);
					this.SendPropertyChanging();
					this._alertTimeline = value;
					this.SendPropertyChanged("alertTimeline");
					this.OnalertTimelineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alertStatus", DbType="Bit")]
		public System.Nullable<bool> alertStatus
		{
			get
			{
				return this._alertStatus;
			}
			set
			{
				if ((this._alertStatus != value))
				{
					this.OnalertStatusChanging(value);
					this.SendPropertyChanging();
					this._alertStatus = value;
					this.SendPropertyChanged("alertStatus");
					this.OnalertStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.departments")]
	public partial class department : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _d_id;
		
		private string _d_name;
		
		private string _d_phone;
		
		private string _d_ext;
		
		private string _d_fax;
		
		private EntitySet<staff> _staffs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ond_idChanging(int value);
    partial void Ond_idChanged();
    partial void Ond_nameChanging(string value);
    partial void Ond_nameChanged();
    partial void Ond_phoneChanging(string value);
    partial void Ond_phoneChanged();
    partial void Ond_extChanging(string value);
    partial void Ond_extChanged();
    partial void Ond_faxChanging(string value);
    partial void Ond_faxChanged();
    #endregion
		
		public department()
		{
			this._staffs = new EntitySet<staff>(new Action<staff>(this.attach_staffs), new Action<staff>(this.detach_staffs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int d_id
		{
			get
			{
				return this._d_id;
			}
			set
			{
				if ((this._d_id != value))
				{
					this.Ond_idChanging(value);
					this.SendPropertyChanging();
					this._d_id = value;
					this.SendPropertyChanged("d_id");
					this.Ond_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d_name", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string d_name
		{
			get
			{
				return this._d_name;
			}
			set
			{
				if ((this._d_name != value))
				{
					this.Ond_nameChanging(value);
					this.SendPropertyChanging();
					this._d_name = value;
					this.SendPropertyChanged("d_name");
					this.Ond_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d_phone", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string d_phone
		{
			get
			{
				return this._d_phone;
			}
			set
			{
				if ((this._d_phone != value))
				{
					this.Ond_phoneChanging(value);
					this.SendPropertyChanging();
					this._d_phone = value;
					this.SendPropertyChanged("d_phone");
					this.Ond_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d_ext", DbType="VarChar(50)")]
		public string d_ext
		{
			get
			{
				return this._d_ext;
			}
			set
			{
				if ((this._d_ext != value))
				{
					this.Ond_extChanging(value);
					this.SendPropertyChanging();
					this._d_ext = value;
					this.SendPropertyChanged("d_ext");
					this.Ond_extChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d_fax", DbType="VarChar(50)")]
		public string d_fax
		{
			get
			{
				return this._d_fax;
			}
			set
			{
				if ((this._d_fax != value))
				{
					this.Ond_faxChanging(value);
					this.SendPropertyChanging();
					this._d_fax = value;
					this.SendPropertyChanged("d_fax");
					this.Ond_faxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="department_staff", Storage="_staffs", ThisKey="d_id", OtherKey="staff_departmentId")]
		public EntitySet<staff> staffs
		{
			get
			{
				return this._staffs;
			}
			set
			{
				this._staffs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_staffs(staff entity)
		{
			this.SendPropertyChanging();
			entity.department = this;
		}
		
		private void detach_staffs(staff entity)
		{
			this.SendPropertyChanging();
			entity.department = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.staffs")]
	public partial class staff : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _staff_id;
		
		private string _staff_fname;
		
		private string _staff_lname;
		
		private string _staff_position;
		
		private string _staff_phone;
		
		private string _staff_ext;
		
		private string _staff_email;
		
		private string _staff_departmentName;
		
		private int _staff_departmentId;
		
		private EntityRef<department> _department;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onstaff_idChanging(int value);
    partial void Onstaff_idChanged();
    partial void Onstaff_fnameChanging(string value);
    partial void Onstaff_fnameChanged();
    partial void Onstaff_lnameChanging(string value);
    partial void Onstaff_lnameChanged();
    partial void Onstaff_positionChanging(string value);
    partial void Onstaff_positionChanged();
    partial void Onstaff_phoneChanging(string value);
    partial void Onstaff_phoneChanged();
    partial void Onstaff_extChanging(string value);
    partial void Onstaff_extChanged();
    partial void Onstaff_emailChanging(string value);
    partial void Onstaff_emailChanged();
    partial void Onstaff_departmentNameChanging(string value);
    partial void Onstaff_departmentNameChanged();
    partial void Onstaff_departmentIdChanging(int value);
    partial void Onstaff_departmentIdChanged();
    #endregion
		
		public staff()
		{
			this._department = default(EntityRef<department>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int staff_id
		{
			get
			{
				return this._staff_id;
			}
			set
			{
				if ((this._staff_id != value))
				{
					this.Onstaff_idChanging(value);
					this.SendPropertyChanging();
					this._staff_id = value;
					this.SendPropertyChanged("staff_id");
					this.Onstaff_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_fname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string staff_fname
		{
			get
			{
				return this._staff_fname;
			}
			set
			{
				if ((this._staff_fname != value))
				{
					this.Onstaff_fnameChanging(value);
					this.SendPropertyChanging();
					this._staff_fname = value;
					this.SendPropertyChanged("staff_fname");
					this.Onstaff_fnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_lname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string staff_lname
		{
			get
			{
				return this._staff_lname;
			}
			set
			{
				if ((this._staff_lname != value))
				{
					this.Onstaff_lnameChanging(value);
					this.SendPropertyChanging();
					this._staff_lname = value;
					this.SendPropertyChanged("staff_lname");
					this.Onstaff_lnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_position", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string staff_position
		{
			get
			{
				return this._staff_position;
			}
			set
			{
				if ((this._staff_position != value))
				{
					this.Onstaff_positionChanging(value);
					this.SendPropertyChanging();
					this._staff_position = value;
					this.SendPropertyChanged("staff_position");
					this.Onstaff_positionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_phone", DbType="VarChar(50)")]
		public string staff_phone
		{
			get
			{
				return this._staff_phone;
			}
			set
			{
				if ((this._staff_phone != value))
				{
					this.Onstaff_phoneChanging(value);
					this.SendPropertyChanging();
					this._staff_phone = value;
					this.SendPropertyChanged("staff_phone");
					this.Onstaff_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_ext", DbType="VarChar(50)")]
		public string staff_ext
		{
			get
			{
				return this._staff_ext;
			}
			set
			{
				if ((this._staff_ext != value))
				{
					this.Onstaff_extChanging(value);
					this.SendPropertyChanging();
					this._staff_ext = value;
					this.SendPropertyChanged("staff_ext");
					this.Onstaff_extChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_email", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string staff_email
		{
			get
			{
				return this._staff_email;
			}
			set
			{
				if ((this._staff_email != value))
				{
					this.Onstaff_emailChanging(value);
					this.SendPropertyChanging();
					this._staff_email = value;
					this.SendPropertyChanged("staff_email");
					this.Onstaff_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_departmentName", DbType="VarChar(150)")]
		public string staff_departmentName
		{
			get
			{
				return this._staff_departmentName;
			}
			set
			{
				if ((this._staff_departmentName != value))
				{
					this.Onstaff_departmentNameChanging(value);
					this.SendPropertyChanging();
					this._staff_departmentName = value;
					this.SendPropertyChanged("staff_departmentName");
					this.Onstaff_departmentNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_departmentId", DbType="Int NOT NULL")]
		public int staff_departmentId
		{
			get
			{
				return this._staff_departmentId;
			}
			set
			{
				if ((this._staff_departmentId != value))
				{
					if (this._department.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onstaff_departmentIdChanging(value);
					this.SendPropertyChanging();
					this._staff_departmentId = value;
					this.SendPropertyChanged("staff_departmentId");
					this.Onstaff_departmentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="department_staff", Storage="_department", ThisKey="staff_departmentId", OtherKey="d_id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public department department
		{
			get
			{
				return this._department.Entity;
			}
			set
			{
				department previousValue = this._department.Entity;
				if (((previousValue != value) 
							|| (this._department.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._department.Entity = null;
						previousValue.staffs.Remove(this);
					}
					this._department.Entity = value;
					if ((value != null))
					{
						value.staffs.Add(this);
						this._staff_departmentId = value.d_id;
					}
					else
					{
						this._staff_departmentId = default(int);
					}
					this.SendPropertyChanged("department");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="temismain.donation")]
	public partial class donation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _first_name;
		
		private string _last_name;
		
		private string _email;
		
		private System.Nullable<decimal> _amount;
		
		private string _message;
		
		private System.Nullable<System.DateTime> _donation_date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onfirst_nameChanging(string value);
    partial void Onfirst_nameChanged();
    partial void Onlast_nameChanging(string value);
    partial void Onlast_nameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnamountChanging(System.Nullable<decimal> value);
    partial void OnamountChanged();
    partial void OnmessageChanging(string value);
    partial void OnmessageChanged();
    partial void Ondonation_dateChanging(System.Nullable<System.DateTime> value);
    partial void Ondonation_dateChanged();
    #endregion
		
		public donation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_name", DbType="VarChar(50)")]
		public string first_name
		{
			get
			{
				return this._first_name;
			}
			set
			{
				if ((this._first_name != value))
				{
					this.Onfirst_nameChanging(value);
					this.SendPropertyChanging();
					this._first_name = value;
					this.SendPropertyChanged("first_name");
					this.Onfirst_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_name", DbType="VarChar(50)")]
		public string last_name
		{
			get
			{
				return this._last_name;
			}
			set
			{
				if ((this._last_name != value))
				{
					this.Onlast_nameChanging(value);
					this.SendPropertyChanging();
					this._last_name = value;
					this.SendPropertyChanged("last_name");
					this.Onlast_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(80)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> amount
		{
			get
			{
				return this._amount;
			}
			set
			{
				if ((this._amount != value))
				{
					this.OnamountChanging(value);
					this.SendPropertyChanging();
					this._amount = value;
					this.SendPropertyChanged("amount");
					this.OnamountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_message", DbType="VarChar(500)")]
		public string message
		{
			get
			{
				return this._message;
			}
			set
			{
				if ((this._message != value))
				{
					this.OnmessageChanging(value);
					this.SendPropertyChanging();
					this._message = value;
					this.SendPropertyChanged("message");
					this.OnmessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donation_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> donation_date
		{
			get
			{
				return this._donation_date;
			}
			set
			{
				if ((this._donation_date != value))
				{
					this.Ondonation_dateChanging(value);
					this.SendPropertyChanging();
					this._donation_date = value;
					this.SendPropertyChanged("donation_date");
					this.Ondonation_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
